import Link from 'next/link';
import Search from '../components/Search';
import catalog from '../.generated/catalog.json';
import stats from '../.generated/stats.json';
import cweTable from '../content/cwe.json';
import kindTemplates from '../content/kind-templates.json';

const languages = [...new Set(catalog.map((entry) => entry.language))];
const languageRows = languages.map((language) => {
  const entries = catalog.filter((entry) => entry.language === language);
  return { language, count: entries.length, packages: [...new Set(entries.map((entry) => entry.package).filter(Boolean))].slice(0, 3) };
}).sort((a, b) => b.count - a.count);
const weaknessRows = Object.keys(cweTable).map((id) => {
  const entries = catalog.filter((entry) => entry.cwe?.includes(id));
  return { id, entryCount: new Set(entries.map((entry) => entry.slug)).size, languages: [...new Set(entries.map((entry) => entry.language))], ...cweTable[id as keyof typeof cweTable] };
}).filter((row) => row.entryCount > 0).sort((a, b) => b.entryCount - a.entryCount).slice(0, 8);
const demo = catalog.find((entry) => entry.method === 'memcpy' && entry.role === 'sink') || catalog[0];
const demoTemplate = kindTemplates[demo.kind as keyof typeof kindTemplates];
const featuredMethods = [...new Map(catalog.map((entry) => [entry.method, entry])).values()].slice(0, 5);

export default function Home() {
  return <main><div className="wrap">
    <section className="hero"><div className="hero-grid"><div><div className="kicker">Which argument is the dangerous one?</div><h1>Look up any API. See the exact argument to watch.</h1><p className="lede">A precise, per-symbol reference built from the Atropos model pack — the tainted slot, the weakness, how an attacker abuses it, and what to check, for {stats.symbols.toLocaleString()} symbols across {languages.join(', ')}.</p><div className="hero-search"><Search /></div><div className="chips"><span className="lab">Try</span>{featuredMethods.map((entry) => <Link className="chip" key={entry.method} href={`/symbols/${entry.slug}`}>{entry.method}</Link>)}</div><div className="funnel-line"><div><span className="a">ATROPOS</span> names the dangerous argument. <span className="l">LACHESIS</span> tells you if it is reachable in your code.</div><p>This reference answers the first for every symbol — then hands you to the engine for the second.</p></div></div><aside className="provcard"><div className="ph">Ingested pack</div><dl><div className="row"><dt>Atropos release</dt><dd>{stats.version}</dd></div><div className="row"><dt>Model facts</dt><dd>{stats.total.toLocaleString()}</dd></div><div className="row"><dt>Symbols</dt><dd>{stats.symbols.toLocaleString()}</dd></div><div className="row"><dt>Languages</dt><dd>{languages.length}</dd></div><div className="row"><dt>Source revision</dt><dd className="git">{stats.source_revision.slice(0, 8)}</dd></div></dl></aside></div></section>
    <section className="browse"><div className="sechead"><div><h2>Do not have a symbol? Start with the danger.</h2><p>The catalog is organized the way you think about risk — by weakness class. Pick one to see every modeled API that reaches it.</p></div><Link className="txtlink" href="/browse">See all {Object.keys(kindTemplates).length} kinds →</Link></div><div className="weakgrid">{weaknessRows.map((row) => <Link className="weakcard" href={`/browse/cwe/${row.id}`} key={row.id}><span className="wk">{row.name}</span><span className="wd">{row.definition}</span><span className="langs">{row.languages.join(' · ')}</span><span className="wf"><span className="cwe">{row.id}</span><span className="cnt">{row.entryCount.toLocaleString()} symbols</span></span></Link>)}</div></section>
    <section className="langs-sec"><div className="sechead"><div><h2>Or start with a language.</h2><p>See which ecosystems the current pack can actually describe.</p></div></div><div className="langrow">{languageRows.slice(0, 4).map((row) => <Link className="langtile" href={`/browse/language/${row.language}`} key={row.language}><div className="lt"><span className="lname">{row.language}</span><span className="lcount">{row.count.toLocaleString()}</span></div><div className="bar"><span style={{ width: `${Math.max(8, Math.round((row.count / languageRows[0].count) * 100))}%` }}/></div><div className="lpk">{row.packages.length ? row.packages.join(' · ') : 'stdlib'} · model facts</div></Link>)}</div></section>
    <section className="demoband"><div className="sechead"><div><h2>Read one record end to end.</h2><p>The observatory answers the first question before a trace begins: what does this symbol do to data?</p></div><Link className="txtlink" href={`/symbols/${demo.slug}`}>Open the {demo.method} record →</Link></div><div className="minicard"><div className="mc-top"><div className="risk-stripe"/><div><div className="mc-sym">{demo.method}</div><div className="mc-env">{demo.language} / {demo.package || 'stdlib'} · {demo.kind}</div></div><span className={`roletag r-${demo.role}`}>{demo.role}</span></div><div className="mc-body"><p className="mc-answer">{demoTemplate?.danger_sentence || demo.notes || `The watched ${demo.access_path || 'argument'} crosses a ${demo.kind} boundary.`}</p><div className="mc-slot">{demo.access_path || 'Argument[0]'} <span className="note">← watched access path</span></div></div></div></section>
    <section className="seamsec"><div className="sechead"><div><h2>Two questions. Two tools.</h2><p>The reference names the boundary precisely, then hands you to the engine for the codebase-level verdict.</p></div></div><div className="seam"><div className="seampanel atr"><div className="sp-tag">Atropos · this site</div><h3>Names the boundary.</h3><div className="sp-sub">A declarative fact about the API itself.</div><ul><li><span className="mk">→</span>Which argument is dangerous, and why.</li><li><span className="mk">→</span>The weakness class and its CWE.</li><li><span className="mk">→</span>How it is abused, and what to check.</li></ul><div className="sp-foot">Same for every one of {stats.symbols.toLocaleString()} symbols.</div></div><div className="seamarrow" aria-hidden="true">→</div><div className="seampanel lac"><div className="sp-tag">Lachesis · the engine</div><h3>Judges the flow.</h3><div className="sp-sub">A verdict about your specific code.</div><ul><li><span className="mk">→</span>Does untrusted data reach that argument?</li><li><span className="mk">→</span>Is a guard already dominating the call?</li><li><span className="mk">→</span>Is this call, in your repo, a real bug?</li></ul><div className="sp-foot">Continue any symbol → <a href="https://lachesis.unboundcompute.com/">Trace it in Lachesis</a></div></div></div><p className="seamnote">Atropos names the argument to watch; only a flow through <i>your</i> codebase can decide if it is reachable.</p></section>
    <footer className="ecofoot"><div className="ep"><a href="https://github.com/UnboundCompute/atropos" className="ext"><b>Atropos</b><span>the model pack</span></a><a href="https://trace.unboundcompute.com/" className="ext"><b>Casefiles</b><span>real vulnerability traces</span></a><a href="https://lachesis.unboundcompute.com/" className="ext"><b>Lachesis</b><span>repository exploration</span></a></div><a className="src" href="https://github.com/UnboundCompute/atropos">Inspect source ↗</a></footer>
  </div></main>;
}
